In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
X = np.array([[1,2],[3,4]])
print('X : \n',X)

X : 
 [[1 2]
 [3 4]]


In [9]:
x3 = np.array([[1,2,3],[3,4,5],[4,3,6]])
x3

array([[1, 2, 3],
       [3, 4, 5],
       [4, 3, 6]])

In [10]:
x3.shape

(3, 3)

In [11]:
x3.size

9

In [12]:
x4=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
x4.shape

(1, 3, 3)

In [14]:
x5=np.array([[1],[2],[3]])
x5

array([[1],
       [2],
       [3]])

In [17]:
x=np.zeros(shape=(2,3),dtype='int')
x

array([[0, 0, 0],
       [0, 0, 0]])

In [21]:
x=np.zeros(shape=(3,3),dtype='int')
x

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [39]:
x=np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
x[4]

54

In [41]:
x[5:10:2]

array([5, 7, 9])

In [43]:
x[-2:]

array([8, 9])

In [44]:
y=x
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
x[-2:]

array([58, 59])

In [45]:
z=x.copy()
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a=np.array([1,2,3])

In [56]:
a

array([1, 2, 3])

In [49]:
b  = np.ndarray(3, dtype='object')

In [50]:
b[:]=a

In [51]:
b

array([1, 2, 3], dtype=object)

In [57]:
b[1]=11

In [58]:
b

array([1, 11, 3], dtype=object)

In [59]:
a

array([1, 2, 3])

In [60]:
a1=a.copy()

In [61]:
a1

array([1, 2, 3])

In [62]:
a1[0]=11

In [63]:
a1

array([11,  2,  3])